{% set name = "lbapcommon" %}
{% set version = "0.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LbAPCommon-{{ version }}.tar.gz
  sha256: 464145d0979b4a81a5bc59c65b173a171ca50832d713c13e8193c4031f36a632

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - setuptools-scm
    - pip
  run:
    - python
    - awkward >=1.0.0
    - jinja2
    - pyyaml
    - boost-histogram
    - hist
    - matplotlib-base
    - setuptools
    - uproot >=4.0.0
    - strictyaml
    - lxml
    - requests
    - keyutils  # [linux]

test:
  imports:
    - LbAPCommon
    - LbAPCommon.linting
    - LbAPCommon.validators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/LbAPCommon
  summary: Common utilities used by LHCb DPA WP2 related software
  dev_url: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/LbAPCommon
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AidanWiederhold
    - chrisburr
