schema_version: 1

context:
  name: lbapcommon
  version: "0.15.3"
  python_min: '3.12'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: b3154871ee7c1bc9aa77faec30b41f43662c3017a097a0e1b871f2f0b81ef7ad

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools-scm
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - strictyaml
    - jinja2
    - lxml
    - pyyaml
    - setuptools
    - boost-histogram
    - hist
    - pandas
    - numpy
    - requests
    - uproot >=5.0.0
    - awkward >=2.1.1
    - matplotlib-base
    - networkx
    - lbdiracwrappers
    - pydantic >=2
    - quickjs
    - cwl-utils
    - cwltool

tests:
  - python:
      imports:
        - LbAPCommon
        - LbAPCommon.linting
        - LbAPCommon.validators
  - requirements:
      run:
        - pip
        - python ${{ python_min }}
    script:
      - pip check
  - script:
      - python test_transform.py
    files:
      recipe:
        - test_transform.py

about:
  summary: Common utilities used by LHCb DPA WP2 related software
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/LbAPCommon
  repository: https://gitlab.cern.ch/lhcb-dpa/analysis-productions/LbAPCommon

extra:
  recipe-maintainers:
    - ryuwd
    - chrisburr
